alias alpine='docker run --rm --name alpine -it alpine /bin/sh'
alias b=brew
alias c=cargo
alias cargo-sort='cargo-sort-ck ./Cargo.toml -w'
alias clock='tock -c -s -C 15'
alias config="edit ~/.zshrc"
alias cs="cargo-sort"
alias dkimgs="docker images"
alias dkps="docker ps"
alias dkpsa="docker ps -a"
alias dkst="docker stats"
alias exot="exit"
alias home="~"
alias lsd="ls -al | lolcat"
alias minify='tr -d "\n\r"'
alias mkv-to-mp4='for f in *.mkv; do ffmpeg -i "$f" -c copy "${f%.mkv}.mp4"; done'
alias n=node
alias neolol='clear && neofetch | lolcat'
alias prune_ds_store='find . -name ".DS_Store" -depth -exec rm {} \;'
alias reload="source ~/.zshrc"
alias send='ffsend'
alias stats='sampler -c ~/.config/sampler.yml'
alias ubuntu='docker run --rm --name ubuntu -it ubuntu /bin/bash'
alias x="exit"
