name: 🔨 Install

on:
  push:
    branches: [ macos, windows, wsl ]

jobs:
  install:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        shell: pwsh
        run: |
          ./install.ps1
