name: 🔨 Install

on:
  push:
    branches: [ master ]

jobs:
  install:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: |
          chmod +x ./install.sh
          ./install.sh
